[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

# [[plugins]]
# # Interactive terminal tool
# repo = 'wkentaro/conque.vim'

[[plugins]]
# roscd & rosed
repo = 'taketwo/vim-ros'
if = 'has("python")'

[[plugins]]
# https://github.com/tpope/vim-repeat
repo = 'tpope/vim-repeat'

[[plugins]]
# https://github.com/nathanaelkane/vim-indent-guides
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
# Surrounding editing
# https://github.com/tpope/vim-surround
repo = 'tpope/vim-surround'

[[plugins]]
# Easy commenting tool
# https://github.com/tomtom/tcomment_vim
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
# git diff, log
# https://github.com/tpope/vim-fugitive
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'idanarye/vim-merginal'

[[plugins]]
repo = 'AndrewRadev/gapply.vim'

[[plugins]]
# https://github.com/gregsexton/gitv
repo = 'gregsexton/gitv'

[[plugins]]
# Open URL
# https://github.com/tyru/open-browser.vim
repo =  'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

# FIXME: neosnippet-snippets won't work with dein.vim
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

[[plugins]]
# RestructuredText
repo = 'Rykka/riv.vim'

[[plugins]]
repo = 'greyblake/vim-preview'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
# Add colorschemes
repo = 'flazz/vim-colorschemes'

[[plugins]]
# python completion
repo = 'davidhalter/jedi-vim'

[[plugins]]
# For HTML and XML
# https://github.com/mattn/emmet-vim
repo = 'mattn/emmet-vim'

[[plugins]]
# https://github.com/othree/html5.vim
repo = 'othree/html5.vim'

[[plugins]]
# For CSS
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
# For JavaScript
repo = 'pangloss/vim-javascript'

[[plugins]]
# Show variables and functions
repo = 'vim-scripts/taglist.vim'

[[plugins]]
# Syntastic Check
# https://github.com/scrooloose/syntastic
repo = 'scrooloose/syntastic'

[[plugins]]
# https://github.com/Rip-Rip/clang_complete
repo = 'Rip-Rip/clang_complete'

[[plugins]]
# https://github.com/greyblake/vim-preview
repo = 'greyblake/vim-preview'

[[plugins]]
# https://github.com/gerw/vim-latex-suite
repo = 'gerw/vim-latex-suite'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'claco/jasmine.vim'

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# [[plugins]]
# repo = 'digitaltoad/vim-pug'

# [[plugins]]
# repo = 'neilagabriel/vim-geeknote'

# [[plugins]]
# repo = 'jaxbot/github-issues.vim'

[[plugins]]
repo = 'hotwatermorning/auto-git-diff'
