[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'taketwo/vim-ros'
if = 'has("python")'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo =  'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'hotwatermorning/auto-git-diff'

[[plugins]]
repo = 'cespare/vim-toml'
