sudo: required

dist: trusty

language: c++

install:
  - sudo apt-get install -qq -y python-setuptools
  - sudo easy_install pip
  - sudo pip install -U pip setuptools
  - sudo pip install PyYaml

script:
  - ./install.py

notifications:
  email: false
