colors:
  default: 0
  light_blue: 1
  blue_green: 2
  purple: 3
  vermilion: 4
  khaki: 5
  orange: 6
  green_blue: 7
  gray: 8
  blue: 9
  green: 10
  red: 11

color_rules:
  purple: [pastime]
  blue: [study, work]
  orange: [univ]
  green: [run]

alias:
  pm: pastime
  sd: study
  std: study
  uv: univ
  unv: univ
  sp: sleep
  slp: sleep
  bt: bath
  bth: bath
  mv: move
  dn: dinner
  wk: work
  wrk: work
  mc: misc
  msc: misc
