vimrc:
  .vimrc
ipython_config.py:
  .ipython/profile_default/ipython_config.py
bashrc:
  .bashrc.wkentaro
colorrc:
  .colorrc
editrc:
  .editrc
emacs.d:
  .emacs.d
events_config.yml:
  .events_config.yml
gitconfig:
  .gitconfig
gitignore_global:
  .gitignore_global
gvimrc:
  .gvimrc
hgignore_global:
  .hgignore_global
inputrc:
  .inputrc
shrc.alias:
  .shrc.alias
percolrc:
  .percol.d/rc.py
pythonstartup:
  .pythonstartup
tmux.conf:
  .tmux.conf
vim:
  .vim
vimrc:
  .vimrc
xinputrc:
  .xinputrc
Xmodmap:
  .Xmodmap
zsh:
  .zsh
zshrc:
  .zshrc.wkentaro
